project_id = "olcygpkghmaqkezmunyu"

[functions.database-backup]
verify_jwt = false

[functions.get-cron-status]
verify_jwt = false

[functions.verify-backup]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.optimize-image]
verify_jwt = false

[functions.get-storage-stats]
verify_jwt = false
