project_id = "olcygpkghmaqkezmunyu"

[functions.database-backup]
verify_jwt = false

[functions.get-cron-status]
verify_jwt = false

[functions.verify-backup]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.optimize-image]
verify_jwt = false

[functions.get-storage-stats]
verify_jwt = false

[functions.improve-bio]
verify_jwt = false

[functions.upload-content]
verify_jwt = false

[functions.delete-content]
verify_jwt = false

[functions.check-content-expiration]
verify_jwt = false

[functions.upload-deliverable]
verify_jwt = false

[functions.check-dispute-deadlines]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-platform-update]
verify_jwt = false

[functions.upload-ad-image]
verify_jwt = false

[functions.check-ad-expiration]
verify_jwt = false

[functions.upload-profile-image]
verify_jwt = false

[functions.upload-portfolio-media]
verify_jwt = false

[functions.send-mass-message]
verify_jwt = false

[functions.upload-site-asset]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.draft-agreement]
verify_jwt = false

[functions.send-push-to-creators]
verify_jwt = false
